variables:
  JUNIT_REPORTER_ENABLED: 1
  JUNIT_REPORTER_RESULT_DIRECTORY: $(Build.SourcesDirectory)

trigger:
- master

pr:
- master

jobs:

- job: Windows
  pool:
    vmImage: 'windows-latest'
    demands: npm
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    displayName: 'Setting up Python version'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x
  - script: npm install npm -g
    displayName: 'Update npm'
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'custom'
      customCommand: 'ci'
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
  - script: python -m pip install --upgrade pip
    displayName: 'Update pip'
  - script: python -m pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python -m pip install https://github.com/morganstanley/testplan/archive/refs/tags/latest.zip
    displayName: 'Install testplan'
    condition: and(succeeded(), and( ne(${{ python.version }}, '2.7'), and( ne(${{ python.version }}, '3.5'), ne(${{ python.version }}, '3.6') ) ) )
  - script: npm run lint
    displayName: 'Linting'
  - script: npm audit --production
    displayName: 'Npm security audit'
    continueOnError: 'true'
  - script: npm test
    displayName: 'Run tests'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(Build.SourcesDirectory)\test-results.xml
      testRunTitle: '$(Agent.JobName), Python $(python.version)'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
    demands: npm
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    displayName: 'Setting up Python version'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'custom'
      customCommand: 'ci'
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
  - script: python -m pip install --upgrade pip
    displayName: 'Update pip'
  - script: python -m pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python -m pip install https://github.com/morganstanley/testplan/archive/refs/tags/latest.zip
    displayName: 'Install testplan'
    condition: and(succeeded(), and( ne(${{ python.version }}, '2.7'), and( ne(${{ python.version }}, '3.5'), ne(${{ python.version }}, '3.6') ) ) )
  - script: npm run lint
    displayName: 'Linting'
  - script: npm audit --production
    displayName: 'Npm security audit'
    continueOnError: 'true'
  - script: VSCODE_PYTHON=$(which python) npm test
    displayName: 'Run tests'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(Build.SourcesDirectory)/test-results.xml
      testRunTitle: '$(Agent.JobName), Python $(python.version)'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
    demands: npm
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    displayName: 'Setting up Python version'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x
  - script: npm install npm -g
    displayName: 'Update npm'
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'custom'
      customCommand: 'ci'
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
  - script: python -m pip install --upgrade pip
    displayName: 'Update pip'
  - script: python -m pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: python -m pip install https://github.com/morganstanley/testplan/archive/refs/tags/latest.zip
    displayName: 'Install testplan'
    condition: and(succeeded(), and( ne(${{ python.version }}, '2.7'), and( ne(${{ python.version }}, '3.5'), ne(${{ python.version }}, '3.6') ) ) )
  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  - script: npm run lint
    displayName: 'Linting'
  - script: npm audit --production
    displayName: 'Npm security audit'
    continueOnError: 'true'
  - script: npm test
    displayName: 'Run tests'
    env:
      DISPLAY: ':99.0'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(Build.SourcesDirectory)/test-results.xml
      testRunTitle: '$(Agent.JobName), Python $(python.version)'
  - script: npm run package
    displayName: 'Package'
  - task: CopyFiles@2
    inputs:
      contents: vscode-python-test-adapter-*.vsix
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Packed extension
